baseURL = "https://ktavabi.github.io/"
languageCode = "en-us"
theme = "awesome-identity"
title = "Kambiz Tavabi"

## Profile Configurations
[params.profile]
portrait = "portrait.jpeg"
firstname = "Kambiz"
lastname = "Tavabi"
title = "Neuroscience Ph.D. / Data Scientist"
bio = """Research Science Engineer with 13+ years of postgraduate experience in biomedical and health data science projects. Expert in behavioral neuroscience, data science, and data engineering. My research focuses on how the human brain learns to acquire and process language. I am proficient in data engineering and analyzing various biomedical imaging technologies (MRI, MEG, EEG). As a trained cognitive psychologist, I work at the intersection of neuroscience and data science to help clinicians reliably diagnose language impairments in psychiatric disorders such as autism. I am a meticulous and passionate worker who seeks translational data science roles in public health, social policy, or healthcare sectors."""


## Contacts Configurations
[params.contacts]
email = "email@kambiztavabi.com"
github = "ktavabi"
stackoverflow = "1634460"
keybase = "ktavabi"
medium = "@ktavabi"
instagram = "ktavabi"
# %TODO: googlescholar = "VO6NMiEAAAAJ\&hl"



## Actions Configurations
[[params.actions]]
name = "Review My CV"
url = "resume.pdf"
#[[params.actions]]
#name = "Ask Me Anything"
#url = "https://github.com/ktavabi/ama"
#[[params.actions]]
#name = "Buy Me a Coffee"
#url = "https://buymeacoff.ee/ktavabi"


## Footer Configurations
[params.footer]
copyright = "© 2022 Kambiz Tavabi. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
poweredBy = true
